export enum ACTIONCREATORS {
  NEW_GOAL = 'NEW_GOAL',
  ADD_NEW_KR = 'ADD_NEW_KR',
  NEW_KR_ACTIVE = 'NEW_KR_ACTIVE',
  NEW_KR_NAME = 'NEW_KR_NAME',
  NEW_KR_HOWITSCALCULATED = 'NEW_KR_HOWITSCALCULATED',
  NEW_KR_INFORMATION = 'NEW_KR_INFORMATION',
  NEW_KR_ATT = 'NEW_KR_ATT',
  NEW_KR_TARGET = 'NEW_KR_TARGET',
  NEW_KR_CURRENT_VALUE = 'NEW_KR_CURRENT_VALUE',
  NEW_KR_PROGRESS = 'NEW_KR_PROGRESS',
}
