export enum ActionCreators {
  NEW_GOAL = "NEW_GOAL",
  NEW_KR_NAME = "NEW_KR_NAME",
  NEW_KR_HOWITSCALCULATED = "NEW_KR_HOWITSCALCULATED",
  NEW_KR_INFORMATION = "NEW_KR_INFORMATION",
  NEW_KR_ATT = "NEW_KR_ATT",
  NEW_KR_TARGET = "NEW_KR_TARGET",
  NEW_KR_CURRENT_VALUE = "NEW_KR_CURRENT_VALUE",
  NEW_KR_PROGRESS = "NEW_KR_PROGRESS",
}
